### ISSUE TITLE
Material are pink with URP in Unity 6 (build 6000.0.21.f1)

### ISSUE THREAD

**Issue by HeadClot** [RadicalCSG/com.chisel#3]
In the latest preview for Unity 6 as of this writing (6000.0.21.f1) the materials that come with Chisel appear pink with the URP pipeline.

Chisel should include a set of URP materials either built in or as a package.

**Comment by LogicalError** [comment]
Thanks for letting us know. We haven't gotten around to make sure everything works with URP / HDRP.

**Comment by LogicalError** [comment]
Fixed in commit 7449fff2a8ce5bddce69eaeeeb42112638026fc5 !
Please let us know if there are still issues
Keep in mind that the sample scene in the package only uses built-in materials atm
